services:
  - type: web
    name: planitshop-chatbot
    env: python
    region: oregon
    buildCommand: pip install -r 01_ChatBot/shopeasy_chatbot/01_chatbot/backend/requirements.txt
    startCommand: cd 01_ChatBot/shopeasy_chatbot/01_chatbot/backend && uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: CHATBOT_MODEL
        value: llama-3.3-70b-versatile
      - key: AMPLIFY_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
